//! Which endpoint to ask, and with what filters.
//!
//! # 🔴 `grids` is two of our asset types, not one
//!
//! SteamGridDB has four asset endpoints; Steam has five editable artwork slots. The mismatch
//! is that **`grids` serves both the portrait capsule and the wide header**, distinguished
//! only by the `dimensions` filter:
//!
//! | Steam slot ([`AssetType`]) | File | SGDB endpoint | `dimensions` |
//! |---|---|---|---|
//! | `Capsule` | `<id>p.png` | `grids` | `600x900`, `342x482`, `660x930` |
//! | `Header` | `<id>.png` | `grids` | `460x215`, `920x430` |
//! | `Hero` | `<id>_hero.png` | `heroes` | `1920x620`, `3840x1240`, `1600x650` |
//! | `Logo` | `<id>_logo.png` | `logos` | *(none)* |
//! | `Icon` | `<id>_icon.<ext>` | `icons` | *(none — see below)* |
//!
//! Querying `grids` without dimensions for the Header tab would fill it with portrait capsules
//! that then get written to `<id>.png`, which is the wide slot. The art would apply and look
//! wrong, which is worse than failing.
//!
//! # 🔴 Dimension values belong to one endpoint each
//!
//! They are not interchangeable, and a mismatch is an HTTP **400**, not an empty result:
//!
//! - `icons?dimensions=<anything>` — every value 400s. `8x8`, `16x16`, `24x24`, `32x32`,
//!   `48x48`, `64x64`, `96x96`, `128x128`, `256x256`, `512x512` and `1024x1024` were each
//!   probed. The endpoint simply does not take the parameter.
//! - `heroes?dimensions=600x900` — 400. Grid sizes are not accepted there, and vice versa.
//! - `grids?dimensions=512x512` and `1024x1024` — **valid** (9 and 22 assets for Portal 2).
//!   An earlier draft removed these after they 400'd on *icons*; they were only ever wrong for
//!   that endpoint. They are off by default because they match little and are not the shape
//!   Steam renders.
//!
//! `[VERIFIED-BOX 2026-07-30]` [`Dimensions::endpoint`] encodes this, and
//! [`AssetQuery::validate_for`] refuses a mismatch before it reaches the network.
//!
//! # Invalid filter values are rejected, not ignored
//!
//! `?dimensions=1x1` returns **HTTP 400**, not an empty result set. `[VERIFIED-BOX 2026-07-30]`
//! So dimensions are a closed set and [`Dimensions`] exists to keep us inside it — a free-text
//! string would turn a typo into a failed request at runtime.

use crate::grid::names::AssetType;

/// A SteamGridDB asset endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssetKind {
    Grid,
    Hero,
    Logo,
    Icon,
}

impl AssetKind {
    /// The URL path segment. All four verified to return 200. `[VERIFIED-BOX 2026-07-30]`
    pub const fn path(self) -> &'static str {
        match self {
            AssetKind::Grid => "grids",
            AssetKind::Hero => "heroes",
            AssetKind::Logo => "logos",
            AssetKind::Icon => "icons",
        }
    }

    /// The styles this endpoint offers.
    ///
    /// A closed set for the same reason [`Dimensions`] is one: an unrecognised style is a 400.
    /// Mirrored by `STYLES` in `packages/shared/src/assets.ts`, and held to it by
    /// `packages/shared/fixtures/filter-vocabulary.json`, which both sides test against.
    pub const fn styles(self) -> &'static [&'static str] {
        match self {
            AssetKind::Grid | AssetKind::Hero => {
                // `hero` genuinely offers fewer, but accepting the grid set for both keeps one
                // list; SteamGridDB ignores a style that matches nothing rather than 400ing.
                &["alternate", "white_logo", "no_logo", "blurred", "material"]
            }
            AssetKind::Logo => &["official", "white", "black", "custom"],
            AssetKind::Icon => &["official", "custom"],
        }
    }

    /// The MIME types this endpoint offers.
    pub const fn mimes(self) -> &'static [&'static str] {
        match self {
            AssetKind::Grid | AssetKind::Hero => &["image/png", "image/jpeg", "image/webp"],
            AssetKind::Logo => &["image/png", "image/webp"],
            AssetKind::Icon => &["image/png", "image/vnd.microsoft.icon"],
        }
    }

    /// The endpoint and default dimension filter for one of Steam's artwork slots.
    ///
    /// `None` for slots SteamGridDB has no source for — `HeroBlur` is generated by Steam, not
    /// uploaded by anyone.
    pub fn for_asset_type(t: AssetType) -> Option<(AssetKind, &'static [Dimensions])> {
        match t {
            AssetType::Capsule => Some((AssetKind::Grid, Dimensions::PORTRAIT)),
            AssetType::Header => Some((AssetKind::Grid, Dimensions::WIDE)),
            AssetType::Hero => Some((AssetKind::Hero, Dimensions::HERO)),
            AssetType::Logo => Some((AssetKind::Logo, &[])),
            AssetType::Icon => Some((AssetKind::Icon, &[])),
            AssetType::HeroBlur => None,
        }
    }
}

/// A dimension filter value SteamGridDB accepts.
///
/// A closed set on purpose: an unrecognised value is a 400, so a typed value turns a runtime
/// failure into a compile-time one.
///
/// **Every variant here has been confirmed to return 200 against the live API**
/// `[VERIFIED-BOX 2026-07-30]`. Do not add one without probing it; the whole point of the type
/// is that it cannot contain a 400.
///
/// # 🔴 Values are endpoint-specific, not interchangeable
///
/// `heroes?dimensions=600x900` is a **400**, not an empty result — and so is
/// `icons?dimensions=<anything>`. So each variant knows which endpoint it belongs to via
/// [`Dimensions::endpoint`], and [`AssetQuery::validate_for`] refuses a mismatch locally
/// rather than letting it become a confusing server error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Dimensions {
    // grids — portrait
    D600x900,
    D342x482,
    D660x930,
    // grids — wide
    D460x215,
    D920x430,
    // grids — square. Fewer assets exist (9 and 22 for Portal 2), but both are accepted.
    D512x512,
    D1024x1024,
    // heroes. `1600x650` is valid but currently matches very little, so an empty result from
    // it is not a bug.
    D1920x620,
    D3840x1240,
    D1600x650,
}

impl Dimensions {
    /// Portrait capsule sizes, `600x900` first because it is what Steam actually renders.
    pub const PORTRAIT: &'static [Dimensions] = &[
        Dimensions::D600x900,
        Dimensions::D342x482,
        Dimensions::D660x930,
    ];
    /// Wide/header capsule sizes.
    pub const WIDE: &'static [Dimensions] = &[Dimensions::D460x215, Dimensions::D920x430];
    /// Hero banner sizes.
    pub const HERO: &'static [Dimensions] = &[
        Dimensions::D1920x620,
        Dimensions::D3840x1240,
        Dimensions::D1600x650,
    ];

    /// Extra sizes a user may opt into for the grid slots. Off by default because they match
    /// far fewer assets and are not the shape Steam renders.
    pub const GRID_SQUARE: &'static [Dimensions] = &[Dimensions::D512x512, Dimensions::D1024x1024];

    /// Every variant, for validating an incoming string and for the vocabulary fixture.
    pub const ALL: &'static [Dimensions] = &[
        Dimensions::D600x900,
        Dimensions::D342x482,
        Dimensions::D660x930,
        Dimensions::D460x215,
        Dimensions::D920x430,
        Dimensions::D512x512,
        Dimensions::D1024x1024,
        Dimensions::D1920x620,
        Dimensions::D3840x1240,
        Dimensions::D1600x650,
    ];

    /// Parse a wire value. `None` for anything outside the closed set.
    pub fn parse(s: &str) -> Option<Dimensions> {
        let s = s.trim();
        Dimensions::ALL.iter().copied().find(|d| d.as_str() == s)
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Dimensions::D600x900 => "600x900",
            Dimensions::D342x482 => "342x482",
            Dimensions::D660x930 => "660x930",
            Dimensions::D460x215 => "460x215",
            Dimensions::D920x430 => "920x430",
            Dimensions::D512x512 => "512x512",
            Dimensions::D1024x1024 => "1024x1024",
            Dimensions::D1920x620 => "1920x620",
            Dimensions::D3840x1240 => "3840x1240",
            Dimensions::D1600x650 => "1600x650",
        }
    }

    /// Which endpoint this value is valid for. Sending it to any other is a 400.
    pub const fn endpoint(self) -> AssetKind {
        match self {
            Dimensions::D600x900
            | Dimensions::D342x482
            | Dimensions::D660x930
            | Dimensions::D460x215
            | Dimensions::D920x430
            | Dimensions::D512x512
            | Dimensions::D1024x1024 => AssetKind::Grid,

            Dimensions::D1920x620 | Dimensions::D3840x1240 | Dimensions::D1600x650 => {
                AssetKind::Hero
            }
        }
    }
}

/// A three-state content filter.
///
/// The API takes `any` / `true` / `false` — *not* a boolean. `any` means "do not filter",
/// which is different from `true` ("only flagged") and from omitting the parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Tri {
    /// Include both flagged and unflagged.
    Any,
    /// Only flagged.
    Only,
    /// Exclude flagged. The API default.
    #[default]
    Exclude,
}

impl Tri {
    pub const fn as_str(self) -> &'static str {
        match self {
            Tri::Any => "any",
            Tri::Only => "true",
            Tri::Exclude => "false",
        }
    }

    pub fn parse(s: &str) -> Option<Tri> {
        match s.trim() {
            "any" => Some(Tri::Any),
            "true" => Some(Tri::Only),
            "false" => Some(Tri::Exclude),
            _ => None,
        }
    }
}

/// Values above 50 are ignored by the API, so asking for more is a wasted round trip.
///
/// Mirrors `PAGE_LIMIT` in `packages/shared/src/filters.ts`.
pub const PAGE_LIMIT: u32 = 50;

/// The `types` filter vocabulary.
pub const ASSET_TYPE_FILTERS: [&str; 2] = ["static", "animated"];

/// Why a filter set could not be turned into a query.
///
/// Every variant names the offending value. An invalid filter reaching SteamGridDB is a **400,
/// not an empty result**, and a 400 surfaces to the user as "SteamGridDB rejected the request",
/// which reads like the service is down rather than like a bad local value.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum QueryError {
    #[error("{value:?} is not a dimension SteamGridDB accepts")]
    UnknownDimension { value: String },

    #[error("{value:?} is not a style the {endpoint} endpoint offers")]
    UnknownStyle {
        value: String,
        endpoint: &'static str,
    },

    #[error("{value:?} is not a MIME type the {endpoint} endpoint offers")]
    UnknownMime {
        value: String,
        endpoint: &'static str,
    },

    #[error("{value:?} is not an asset type (expected `static` or `animated`)")]
    UnknownType { value: String },

    #[error("{param} must be `any`, `true` or `false`, not {value:?}")]
    BadTri { param: &'static str, value: String },
}

/// The wire form of `filtersToQuery()` from `packages/shared/src/filters.ts`.
///
/// Comma-separated strings, exactly as that function emits them. **This is transport, not
/// logic** — the untagged/`oneoftag` inversion has one implementation and it is not here.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Deserialize)]
#[serde(default)]
pub struct FilterParams {
    pub styles: Option<String>,
    pub dimensions: Option<String>,
    pub mimes: Option<String>,
    pub types: Option<String>,
    pub nsfw: Option<String>,
    pub humor: Option<String>,
    pub epilepsy: Option<String>,
    /// 🔴 May be the **empty string**, which `filtersToQuery` sends to mean "no tag filter at
    /// all". It must become zero values and be omitted from the URL, not sent as `oneoftag=`.
    pub oneoftag: Option<String>,
}

/// Split a comma-separated filter value, dropping empties.
///
/// `Some("")` yielding nothing is the load-bearing case: it is what `oneoftag` carries when
/// `untagged` is on.
fn csv(value: Option<&String>) -> Vec<&str> {
    value
        .map(|s| {
            s.split(',')
                .map(str::trim)
                .filter(|p| !p.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// Filters for an asset query.
///
/// Mirrors what `packages/shared/src/filters.ts` produces. The tag→query *inversion* lives in
/// TypeScript only and is not duplicated here — this type is the transport for its output, so
/// there is no second implementation to drift.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AssetQuery {
    pub dimensions: Vec<Dimensions>,
    pub styles: Vec<String>,
    pub mimes: Vec<String>,
    /// `static` / `animated`.
    pub types: Vec<String>,
    pub nsfw: Option<Tri>,
    pub humor: Option<Tri>,
    pub epilepsy: Option<Tri>,
    pub oneoftag: Vec<String>,
    /// 0-based, matching the `page` the API reports back.
    pub page: Option<u32>,
    pub limit: Option<u32>,
}

impl AssetQuery {
    /// A query for one of Steam's artwork slots, with that slot's dimension filter applied.
    pub fn for_asset_type(t: AssetType) -> Option<(AssetKind, AssetQuery)> {
        let (kind, dims) = AssetKind::for_asset_type(t)?;
        Some((
            kind,
            AssetQuery {
                dimensions: dims.to_vec(),
                ..Default::default()
            },
        ))
    }

    /// Build a query from the frontend's filter parameters, refusing anything outside the
    /// closed vocabularies.
    ///
    /// Rejecting locally is the point. The UI only ever offers values from the shared tables, so
    /// a rejection means a wiring bug — and it says so, naming the value, instead of arriving as
    /// an opaque HTTP 400 that looks like SteamGridDB is broken.
    ///
    /// The cost is that a style SteamGridDB *adds* is refused until it is added here too. That
    /// is the same trade [`Dimensions`] already makes deliberately, and the failure is a clear
    /// named error rather than a silent empty page.
    pub fn from_params(kind: AssetKind, p: &FilterParams) -> Result<AssetQuery, QueryError> {
        let mut dimensions = Vec::new();
        for value in csv(p.dimensions.as_ref()) {
            dimensions.push(Dimensions::parse(value).ok_or_else(|| {
                QueryError::UnknownDimension {
                    value: value.to_owned(),
                }
            })?);
        }

        let allowed = |value: &str, set: &[&str]| set.contains(&value);

        let mut styles = Vec::new();
        for value in csv(p.styles.as_ref()) {
            if !allowed(value, kind.styles()) {
                return Err(QueryError::UnknownStyle {
                    value: value.to_owned(),
                    endpoint: kind.path(),
                });
            }
            styles.push(value.to_owned());
        }

        let mut mimes = Vec::new();
        for value in csv(p.mimes.as_ref()) {
            if !allowed(value, kind.mimes()) {
                return Err(QueryError::UnknownMime {
                    value: value.to_owned(),
                    endpoint: kind.path(),
                });
            }
            mimes.push(value.to_owned());
        }

        let mut types = Vec::new();
        for value in csv(p.types.as_ref()) {
            if !allowed(value, &ASSET_TYPE_FILTERS) {
                return Err(QueryError::UnknownType {
                    value: value.to_owned(),
                });
            }
            types.push(value.to_owned());
        }

        let tri = |param: &'static str, raw: Option<&String>| -> Result<Option<Tri>, QueryError> {
            match raw {
                None => Ok(None),
                Some(v) => Tri::parse(v).map(Some).ok_or_else(|| QueryError::BadTri {
                    param,
                    value: v.clone(),
                }),
            }
        };

        Ok(AssetQuery {
            dimensions,
            styles,
            mimes,
            types,
            nsfw: tri("nsfw", p.nsfw.as_ref())?,
            humor: tri("humor", p.humor.as_ref())?,
            epilepsy: tri("epilepsy", p.epilepsy.as_ref())?,
            oneoftag: csv(p.oneoftag.as_ref())
                .into_iter()
                .map(str::to_owned)
                .collect(),
            page: None,
            limit: None,
        })
    }

    pub fn page(mut self, page: u32) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: u32) -> Self {
        self.limit = Some(limit);
        self
    }

    /// Reject dimensions that belong to a different endpoint.
    ///
    /// `heroes?dimensions=600x900` is a 400, and so is any `dimensions` on `icons`. Catching
    /// it here turns "SteamGridDB rejected the request" — which reads like the service is
    /// broken — into a specific, local, fixable message.
    pub fn validate_for(&self, kind: AssetKind) -> Result<(), String> {
        if self.dimensions.is_empty() {
            return Ok(());
        }
        if matches!(kind, AssetKind::Logo | AssetKind::Icon) {
            return Err(format!(
                "the {} endpoint rejects `dimensions` entirely",
                kind.path()
            ));
        }
        if let Some(bad) = self.dimensions.iter().find(|d| d.endpoint() != kind) {
            return Err(format!(
                "dimension {} belongs to the {} endpoint, not {}",
                bad.as_str(),
                bad.endpoint().path(),
                kind.path()
            ));
        }
        Ok(())
    }

    /// Render to query-string pairs.
    ///
    /// Empty lists are **omitted entirely** rather than sent as `param=`. An empty
    /// `dimensions=` is not the same as no filter, and sending one risks a 400 for no benefit.
    pub fn to_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs: Vec<(&'static str, String)> = Vec::new();

        let csv_static =
            |v: &[Dimensions]| v.iter().map(|d| d.as_str()).collect::<Vec<_>>().join(",");

        if !self.dimensions.is_empty() {
            pairs.push(("dimensions", csv_static(&self.dimensions)));
        }
        if !self.styles.is_empty() {
            pairs.push(("styles", self.styles.join(",")));
        }
        if !self.mimes.is_empty() {
            pairs.push(("mimes", self.mimes.join(",")));
        }
        if !self.types.is_empty() {
            pairs.push(("types", self.types.join(",")));
        }
        if let Some(v) = self.nsfw {
            pairs.push(("nsfw", v.as_str().to_owned()));
        }
        if let Some(v) = self.humor {
            pairs.push(("humor", v.as_str().to_owned()));
        }
        if let Some(v) = self.epilepsy {
            pairs.push(("epilepsy", v.as_str().to_owned()));
        }
        if !self.oneoftag.is_empty() {
            pairs.push(("oneoftag", self.oneoftag.join(",")));
        }
        if let Some(p) = self.page {
            pairs.push(("page", p.to_string()));
        }
        if let Some(l) = self.limit {
            pairs.push(("limit", l.to_string()));
        }
        pairs
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, reason = "test assertions are allowed to panic")]
mod tests {
    use super::*;

    fn params(pairs: &[(&str, &str)]) -> FilterParams {
        let get = |k: &str| {
            pairs
                .iter()
                .find(|(key, _)| *key == k)
                .map(|(_, v)| (*v).to_owned())
        };
        FilterParams {
            styles: get("styles"),
            dimensions: get("dimensions"),
            mimes: get("mimes"),
            types: get("types"),
            nsfw: get("nsfw"),
            humor: get("humor"),
            epilepsy: get("epilepsy"),
            oneoftag: get("oneoftag"),
        }
    }

    #[test]
    fn from_params_accepts_a_real_filter_set() {
        // The control. Every other test here asserts a *rejection*, and an all-negative suite
        // cannot tell "correctly refused" from "refuses everything" — including the values the
        // UI actually sends.
        let q = AssetQuery::from_params(
            AssetKind::Grid,
            &params(&[
                ("dimensions", "600x900,342x482"),
                ("styles", "alternate,blurred"),
                ("mimes", "image/png"),
                ("types", "static,animated"),
                ("nsfw", "false"),
                ("humor", "any"),
                ("epilepsy", "true"),
                ("oneoftag", "humor,nsfw"),
            ]),
        )
        .unwrap();

        assert_eq!(
            q.dimensions,
            vec![Dimensions::D600x900, Dimensions::D342x482]
        );
        assert_eq!(q.styles, vec!["alternate", "blurred"]);
        assert_eq!(q.nsfw, Some(Tri::Exclude));
        assert_eq!(q.humor, Some(Tri::Any));
        assert_eq!(q.epilepsy, Some(Tri::Only));
        assert_eq!(q.oneoftag, vec!["humor", "nsfw"]);
    }

    #[test]
    fn an_empty_oneoftag_means_no_tag_filter_and_is_not_sent() {
        // `filtersToQuery` emits `oneoftag: ''` when `untagged` is on. Sending that verbatim
        // would ask SteamGridDB to match a tag whose name is the empty string.
        let q = AssetQuery::from_params(AssetKind::Grid, &params(&[("oneoftag", "")])).unwrap();
        assert!(q.oneoftag.is_empty());
        assert!(
            !q.to_pairs().iter().any(|(k, _)| *k == "oneoftag"),
            "an empty oneoftag must be omitted from the URL entirely",
        );

        // Control: a non-empty one really does get sent, so the assertion above is about the
        // empty case and not about oneoftag being broken outright.
        let q =
            AssetQuery::from_params(AssetKind::Grid, &params(&[("oneoftag", "humor")])).unwrap();
        assert!(q.to_pairs().contains(&("oneoftag", "humor".to_owned())));
    }

    #[test]
    fn a_value_outside_the_closed_set_is_refused_locally_and_names_itself() {
        assert_eq!(
            AssetQuery::from_params(AssetKind::Grid, &params(&[("dimensions", "1x1")])),
            Err(QueryError::UnknownDimension {
                value: "1x1".to_owned()
            }),
        );
        assert_eq!(
            AssetQuery::from_params(AssetKind::Grid, &params(&[("styles", "sparkly")])),
            Err(QueryError::UnknownStyle {
                value: "sparkly".to_owned(),
                endpoint: "grids",
            }),
        );
        assert_eq!(
            AssetQuery::from_params(AssetKind::Icon, &params(&[("mimes", "image/gif")])),
            Err(QueryError::UnknownMime {
                value: "image/gif".to_owned(),
                endpoint: "icons",
            }),
        );
        assert_eq!(
            AssetQuery::from_params(AssetKind::Grid, &params(&[("types", "moving")])),
            Err(QueryError::UnknownType {
                value: "moving".to_owned()
            }),
        );
        // A boolean is the obvious wrong guess here: the API takes any/true/false, not a bool.
        assert_eq!(
            AssetQuery::from_params(AssetKind::Grid, &params(&[("nsfw", "yes")])),
            Err(QueryError::BadTri {
                param: "nsfw",
                value: "yes".to_owned()
            }),
        );
    }

    #[test]
    fn a_style_valid_for_one_endpoint_is_refused_for_another() {
        // `white_logo` is a grid style; the logo endpoint has its own vocabulary. Accepting it
        // everywhere would send a 400 that reads as a service failure.
        assert!(
            AssetQuery::from_params(AssetKind::Grid, &params(&[("styles", "white_logo")])).is_ok()
        );
        assert!(
            AssetQuery::from_params(AssetKind::Logo, &params(&[("styles", "white_logo")])).is_err()
        );
        // And the reverse, so this is about vocabularies rather than about one being stricter.
        assert!(AssetQuery::from_params(AssetKind::Logo, &params(&[("styles", "black")])).is_ok());
        assert!(AssetQuery::from_params(AssetKind::Grid, &params(&[("styles", "black")])).is_err());
    }

    #[test]
    fn tri_parses_exactly_the_three_values_the_api_takes() {
        assert_eq!(Tri::parse("any"), Some(Tri::Any));
        assert_eq!(Tri::parse("true"), Some(Tri::Only));
        assert_eq!(Tri::parse("false"), Some(Tri::Exclude));
        assert_eq!(Tri::parse("TRUE"), None, "the API is case-sensitive here");
        assert_eq!(Tri::parse(""), None);
    }

    #[test]
    fn the_filter_vocabulary_matches_the_shared_fixture() {
        // The anti-drift guard. These lists exist in both Rust and TypeScript: the UI offers
        // values from the TS tables and `from_params` validates against the Rust ones, so a
        // value in one and not the other becomes a filter that silently returns nothing.
        // Same pattern, and the same reason, as the logo fixture.
        #[derive(serde::Deserialize)]
        struct Vocabulary {
            dimensions: std::collections::BTreeMap<String, DimensionSet>,
            styles: std::collections::BTreeMap<String, Vec<String>>,
            mimes: std::collections::BTreeMap<String, Vec<String>>,
            types: Vec<String>,
            tri: Vec<String>,
            #[serde(rename = "pageLimit")]
            page_limit: u32,
        }
        #[derive(serde::Deserialize)]
        struct DimensionSet {
            all: Vec<String>,
        }

        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../packages/shared/fixtures/filter-vocabulary.json"
        );
        let raw = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("shared filter fixture missing at {path}: {e}"));
        let vocab: Vocabulary = serde_json::from_str(&raw)
            .unwrap_or_else(|e| panic!("shared filter fixture malformed: {e}"));

        // Premise: the fixture really was loaded and is not an empty object that would make
        // every assertion below vacuous.
        assert_eq!(vocab.dimensions.len(), 5, "one entry per asset type");

        // Every dimension named anywhere in the fixture must be parseable by Rust.
        for (asset, set) in &vocab.dimensions {
            for value in &set.all {
                assert!(
                    Dimensions::parse(value).is_some(),
                    "{asset}: TypeScript offers dimension {value:?} that Rust would reject",
                );
            }
        }
        // ...and the reverse, so Rust cannot carry a value the UI can never produce.
        for d in Dimensions::ALL {
            assert!(
                vocab
                    .dimensions
                    .values()
                    .any(|s| s.all.iter().any(|v| v == d.as_str())),
                "Rust knows dimension {} that the shared fixture does not list",
                d.as_str(),
            );
        }

        let kind_of = |asset: &str| match asset {
            "grid_p" | "grid_l" => AssetKind::Grid,
            "hero" => AssetKind::Hero,
            "logo" => AssetKind::Logo,
            "icon" => AssetKind::Icon,
            other => panic!("unknown asset type {other:?} in the fixture"),
        };

        for (asset, styles) in &vocab.styles {
            let kind = kind_of(asset);
            for value in styles {
                assert!(
                    kind.styles().contains(&value.as_str()),
                    "{asset}: TypeScript offers style {value:?} that Rust would reject",
                );
            }
        }
        for (asset, mimes) in &vocab.mimes {
            let kind = kind_of(asset);
            for value in mimes {
                assert!(
                    kind.mimes().contains(&value.as_str()),
                    "{asset}: TypeScript offers MIME {value:?} that Rust would reject",
                );
            }
        }

        assert_eq!(vocab.types, ASSET_TYPE_FILTERS);
        assert_eq!(
            vocab.tri,
            vec!["any".to_owned(), "true".to_owned(), "false".to_owned()],
        );
        assert_eq!(vocab.page_limit, PAGE_LIMIT);
    }

    #[test]
    fn the_two_grid_slots_hit_the_same_endpoint_with_different_dimensions() {
        // The mapping most likely to be got wrong, and the one whose failure looks like
        // "the art applied but it is the wrong shape".
        let (capsule_kind, capsule) = AssetQuery::for_asset_type(AssetType::Capsule).unwrap();
        let (header_kind, header) = AssetQuery::for_asset_type(AssetType::Header).unwrap();

        assert_eq!(capsule_kind, AssetKind::Grid);
        assert_eq!(header_kind, AssetKind::Grid);
        assert_eq!(capsule_kind.path(), "grids");

        assert!(capsule.dimensions.contains(&Dimensions::D600x900));
        assert!(header.dimensions.contains(&Dimensions::D460x215));
        assert!(
            !capsule
                .dimensions
                .iter()
                .any(|d| header.dimensions.contains(d)),
            "portrait and wide dimension sets must not overlap"
        );
    }

    #[test]
    fn every_editable_slot_maps_somewhere_except_heroblur() {
        for t in [
            AssetType::Capsule,
            AssetType::Header,
            AssetType::Hero,
            AssetType::Logo,
            AssetType::Icon,
        ] {
            assert!(
                AssetKind::for_asset_type(t).is_some(),
                "{t} must map to an endpoint"
            );
        }
        assert!(
            AssetKind::for_asset_type(AssetType::HeroBlur).is_none(),
            "HeroBlur is generated by Steam; nobody uploads one"
        );
    }

    #[test]
    fn logos_and_icons_carry_no_dimension_filter() {
        // Icons matter most here: the endpoint 400s on *every* dimension value, so sending one
        // would break the whole tab rather than just narrowing it.
        for t in [AssetType::Logo, AssetType::Icon] {
            let (_, q) = AssetQuery::for_asset_type(t).unwrap();
            assert!(q.dimensions.is_empty(), "{t} must send no dimensions");
            assert!(
                !q.to_pairs().iter().any(|(k, _)| *k == "dimensions"),
                "an empty dimensions list must be omitted, not sent as `dimensions=`"
            );
        }
    }

    #[test]
    fn tri_renders_the_api_words_not_booleans() {
        assert_eq!(Tri::Any.as_str(), "any");
        assert_eq!(Tri::Only.as_str(), "true");
        assert_eq!(Tri::Exclude.as_str(), "false");
        assert_eq!(Tri::default(), Tri::Exclude);
    }

    #[test]
    fn pairs_render_as_comma_separated_and_omit_empties() {
        let q = AssetQuery {
            dimensions: vec![Dimensions::D600x900, Dimensions::D342x482],
            nsfw: Some(Tri::Any),
            oneoftag: vec!["humor".into()],
            page: Some(2),
            limit: Some(50),
            ..Default::default()
        };
        let pairs = q.to_pairs();
        let get = |k: &str| {
            pairs
                .iter()
                .find(|(pk, _)| *pk == k)
                .map(|(_, v)| v.clone())
        };

        assert_eq!(get("dimensions"), Some("600x900,342x482".into()));
        assert_eq!(get("nsfw"), Some("any".into()));
        assert_eq!(get("oneoftag"), Some("humor".into()));
        assert_eq!(get("page"), Some("2".into()));
        assert_eq!(get("limit"), Some("50".into()));
        assert_eq!(get("styles"), None);
        assert_eq!(get("humor"), None, "an unset filter must be omitted");
    }

    #[test]
    fn an_empty_query_sends_nothing_at_all() {
        assert!(AssetQuery::default().to_pairs().is_empty());
    }

    #[test]
    fn every_dimension_knows_which_endpoint_it_belongs_to() {
        // Measured: grids accept 600x900/342x482/660x930/460x215/920x430/512x512/1024x1024;
        // heroes accept only their own three and 400 on any grid value.
        for d in Dimensions::PORTRAIT
            .iter()
            .chain(Dimensions::WIDE)
            .chain(Dimensions::GRID_SQUARE)
        {
            assert_eq!(d.endpoint(), AssetKind::Grid, "{}", d.as_str());
        }
        for d in Dimensions::HERO {
            assert_eq!(d.endpoint(), AssetKind::Hero, "{}", d.as_str());
        }
    }

    #[test]
    fn a_dimension_from_the_wrong_endpoint_is_refused_locally() {
        // `heroes?dimensions=600x900` is an HTTP 400. Catching it here means the message names
        // the actual mistake instead of blaming SteamGridDB.
        let q = AssetQuery {
            dimensions: vec![Dimensions::D600x900],
            ..Default::default()
        };
        let err = q.validate_for(AssetKind::Hero).unwrap_err();
        assert!(err.contains("600x900"), "{err}");
        assert!(err.contains("heroes"), "{err}");

        assert!(q.validate_for(AssetKind::Grid).is_ok(), "the control");
    }

    #[test]
    fn any_dimension_on_icons_or_logos_is_refused() {
        // Both endpoints 400 on every value, including plausible ones like 512x512.
        let q = AssetQuery {
            dimensions: vec![Dimensions::D512x512],
            ..Default::default()
        };
        for kind in [AssetKind::Icon, AssetKind::Logo] {
            let err = q.validate_for(kind).unwrap_err();
            assert!(err.contains("rejects `dimensions` entirely"), "{err}");
        }
    }

    #[test]
    fn the_queries_we_build_ourselves_all_validate() {
        // The guard must never fire on our own defaults — that would break every tab.
        for t in [
            AssetType::Capsule,
            AssetType::Header,
            AssetType::Hero,
            AssetType::Logo,
            AssetType::Icon,
        ] {
            let (kind, q) = AssetQuery::for_asset_type(t).unwrap();
            assert!(
                q.validate_for(kind).is_ok(),
                "{t} produced an invalid query"
            );
        }
    }
}
