//! Which endpoint to ask, and with what filters.
//!
//! # 🔴 `grids` is two of our asset types, not one
//!
//! SteamGridDB has four asset endpoints; Steam has five editable artwork slots. The mismatch
//! is that **`grids` serves both the portrait capsule and the wide header**, distinguished
//! only by the `dimensions` filter:
//!
//! | Steam slot ([`AssetType`]) | File | SGDB endpoint | `dimensions` |
//! |---|---|---|---|
//! | `Capsule` | `<id>p.png` | `grids` | `600x900`, `342x482`, `660x930` |
//! | `Header` | `<id>.png` | `grids` | `460x215`, `920x430` |
//! | `Hero` | `<id>_hero.png` | `heroes` | `1920x620`, `3840x1240`, `1600x650` |
//! | `Logo` | `<id>_logo.png` | `logos` | *(none)* |
//! | `Icon` | `<id>_icon.<ext>` | `icons` | *(none — see below)* |
//!
//! # 🔴 `icons` rejects `dimensions` outright
//!
//! Not "ignores it" — **every** value returns HTTP 400, including plausible icon sizes:
//! `8x8`, `16x16`, `24x24`, `32x32`, `48x48`, `64x64`, `96x96`, `128x128`, `256x256`,
//! `512x512` and `1024x1024` were each probed and each 400'd. `[VERIFIED-BOX 2026-07-30]`
//!
//! An earlier draft of this file carried `512x512` and `1024x1024` as icon dimensions on the
//! strength of them merely sounding right. They are gone rather than commented out: a value
//! that cannot be constructed cannot be sent.
//!
//! Querying `grids` without dimensions for the Header tab would fill it with portrait capsules
//! that then get written to `<id>.png`, which is the wide slot. The art would apply and look
//! wrong, which is worse than failing.
//!
//! # Invalid filter values are rejected, not ignored
//!
//! `?dimensions=1x1` returns **HTTP 400**, not an empty result set. `[VERIFIED-BOX 2026-07-30]`
//! So dimensions are a closed set and [`Dimensions`] exists to keep us inside it — a free-text
//! string would turn a typo into a failed request at runtime.

use crate::grid::names::AssetType;

/// A SteamGridDB asset endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssetKind {
    Grid,
    Hero,
    Logo,
    Icon,
}

impl AssetKind {
    /// The URL path segment. All four verified to return 200. `[VERIFIED-BOX 2026-07-30]`
    pub const fn path(self) -> &'static str {
        match self {
            AssetKind::Grid => "grids",
            AssetKind::Hero => "heroes",
            AssetKind::Logo => "logos",
            AssetKind::Icon => "icons",
        }
    }

    /// The endpoint and default dimension filter for one of Steam's artwork slots.
    ///
    /// `None` for slots SteamGridDB has no source for — `HeroBlur` is generated by Steam, not
    /// uploaded by anyone.
    pub fn for_asset_type(t: AssetType) -> Option<(AssetKind, &'static [Dimensions])> {
        match t {
            AssetType::Capsule => Some((AssetKind::Grid, Dimensions::PORTRAIT)),
            AssetType::Header => Some((AssetKind::Grid, Dimensions::WIDE)),
            AssetType::Hero => Some((AssetKind::Hero, Dimensions::HERO)),
            AssetType::Logo => Some((AssetKind::Logo, &[])),
            AssetType::Icon => Some((AssetKind::Icon, &[])),
            AssetType::HeroBlur => None,
        }
    }
}

/// A dimension filter value SteamGridDB accepts.
///
/// A closed set on purpose: an unrecognised value is a 400, so a typed value turns a runtime
/// failure into a compile-time one.
///
/// **Every variant here has been confirmed to return 200 against the live API**
/// `[VERIFIED-BOX 2026-07-30]`. Two speculative icon sizes (`512x512`, `1024x1024`) were in an
/// earlier draft and are deliberately gone — see [`AssetKind::Icon`] below. Do not add a value
/// without probing it; the whole point of the type is that it cannot contain a 400.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Dimensions {
    // grids — portrait
    D600x900,
    D342x482,
    D660x930,
    // grids — wide
    D460x215,
    D920x430,
    // heroes.  `1600x650` is valid but currently matches very little, so an empty result from
    // it is not a bug.
    D1920x620,
    D3840x1240,
    D1600x650,
}

impl Dimensions {
    /// Portrait capsule sizes, `600x900` first because it is what Steam actually renders.
    pub const PORTRAIT: &'static [Dimensions] = &[
        Dimensions::D600x900,
        Dimensions::D342x482,
        Dimensions::D660x930,
    ];
    /// Wide/header capsule sizes.
    pub const WIDE: &'static [Dimensions] = &[Dimensions::D460x215, Dimensions::D920x430];
    /// Hero banner sizes.
    pub const HERO: &'static [Dimensions] = &[
        Dimensions::D1920x620,
        Dimensions::D3840x1240,
        Dimensions::D1600x650,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Dimensions::D600x900 => "600x900",
            Dimensions::D342x482 => "342x482",
            Dimensions::D660x930 => "660x930",
            Dimensions::D460x215 => "460x215",
            Dimensions::D920x430 => "920x430",
            Dimensions::D1920x620 => "1920x620",
            Dimensions::D3840x1240 => "3840x1240",
            Dimensions::D1600x650 => "1600x650",
        }
    }
}

/// A three-state content filter.
///
/// The API takes `any` / `true` / `false` — *not* a boolean. `any` means "do not filter",
/// which is different from `true` ("only flagged") and from omitting the parameter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Tri {
    /// Include both flagged and unflagged.
    Any,
    /// Only flagged.
    Only,
    /// Exclude flagged. The API default.
    #[default]
    Exclude,
}

impl Tri {
    pub const fn as_str(self) -> &'static str {
        match self {
            Tri::Any => "any",
            Tri::Only => "true",
            Tri::Exclude => "false",
        }
    }
}

/// Filters for an asset query.
///
/// Mirrors what `packages/shared/src/filters.ts` produces. The tag→query *inversion* lives in
/// TypeScript only and is not duplicated here — this type is the transport for its output, so
/// there is no second implementation to drift.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AssetQuery {
    pub dimensions: Vec<Dimensions>,
    pub styles: Vec<String>,
    pub mimes: Vec<String>,
    /// `static` / `animated`.
    pub types: Vec<String>,
    pub nsfw: Option<Tri>,
    pub humor: Option<Tri>,
    pub epilepsy: Option<Tri>,
    pub oneoftag: Vec<String>,
    /// 0-based, matching the `page` the API reports back.
    pub page: Option<u32>,
    pub limit: Option<u32>,
}

impl AssetQuery {
    /// A query for one of Steam's artwork slots, with that slot's dimension filter applied.
    pub fn for_asset_type(t: AssetType) -> Option<(AssetKind, AssetQuery)> {
        let (kind, dims) = AssetKind::for_asset_type(t)?;
        Some((
            kind,
            AssetQuery {
                dimensions: dims.to_vec(),
                ..Default::default()
            },
        ))
    }

    pub fn page(mut self, page: u32) -> Self {
        self.page = Some(page);
        self
    }

    pub fn limit(mut self, limit: u32) -> Self {
        self.limit = Some(limit);
        self
    }

    /// Render to query-string pairs.
    ///
    /// Empty lists are **omitted entirely** rather than sent as `param=`. An empty
    /// `dimensions=` is not the same as no filter, and sending one risks a 400 for no benefit.
    pub fn to_pairs(&self) -> Vec<(&'static str, String)> {
        let mut pairs: Vec<(&'static str, String)> = Vec::new();

        let csv_static =
            |v: &[Dimensions]| v.iter().map(|d| d.as_str()).collect::<Vec<_>>().join(",");

        if !self.dimensions.is_empty() {
            pairs.push(("dimensions", csv_static(&self.dimensions)));
        }
        if !self.styles.is_empty() {
            pairs.push(("styles", self.styles.join(",")));
        }
        if !self.mimes.is_empty() {
            pairs.push(("mimes", self.mimes.join(",")));
        }
        if !self.types.is_empty() {
            pairs.push(("types", self.types.join(",")));
        }
        if let Some(v) = self.nsfw {
            pairs.push(("nsfw", v.as_str().to_owned()));
        }
        if let Some(v) = self.humor {
            pairs.push(("humor", v.as_str().to_owned()));
        }
        if let Some(v) = self.epilepsy {
            pairs.push(("epilepsy", v.as_str().to_owned()));
        }
        if !self.oneoftag.is_empty() {
            pairs.push(("oneoftag", self.oneoftag.join(",")));
        }
        if let Some(p) = self.page {
            pairs.push(("page", p.to_string()));
        }
        if let Some(l) = self.limit {
            pairs.push(("limit", l.to_string()));
        }
        pairs
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, reason = "test assertions are allowed to panic")]
mod tests {
    use super::*;

    #[test]
    fn the_two_grid_slots_hit_the_same_endpoint_with_different_dimensions() {
        // The mapping most likely to be got wrong, and the one whose failure looks like
        // "the art applied but it is the wrong shape".
        let (capsule_kind, capsule) = AssetQuery::for_asset_type(AssetType::Capsule).unwrap();
        let (header_kind, header) = AssetQuery::for_asset_type(AssetType::Header).unwrap();

        assert_eq!(capsule_kind, AssetKind::Grid);
        assert_eq!(header_kind, AssetKind::Grid);
        assert_eq!(capsule_kind.path(), "grids");

        assert!(capsule.dimensions.contains(&Dimensions::D600x900));
        assert!(header.dimensions.contains(&Dimensions::D460x215));
        assert!(
            !capsule
                .dimensions
                .iter()
                .any(|d| header.dimensions.contains(d)),
            "portrait and wide dimension sets must not overlap"
        );
    }

    #[test]
    fn every_editable_slot_maps_somewhere_except_heroblur() {
        for t in [
            AssetType::Capsule,
            AssetType::Header,
            AssetType::Hero,
            AssetType::Logo,
            AssetType::Icon,
        ] {
            assert!(
                AssetKind::for_asset_type(t).is_some(),
                "{t} must map to an endpoint"
            );
        }
        assert!(
            AssetKind::for_asset_type(AssetType::HeroBlur).is_none(),
            "HeroBlur is generated by Steam; nobody uploads one"
        );
    }

    #[test]
    fn logos_and_icons_carry_no_dimension_filter() {
        // Icons matter most here: the endpoint 400s on *every* dimension value, so sending one
        // would break the whole tab rather than just narrowing it.
        for t in [AssetType::Logo, AssetType::Icon] {
            let (_, q) = AssetQuery::for_asset_type(t).unwrap();
            assert!(q.dimensions.is_empty(), "{t} must send no dimensions");
            assert!(
                !q.to_pairs().iter().any(|(k, _)| *k == "dimensions"),
                "an empty dimensions list must be omitted, not sent as `dimensions=`"
            );
        }
    }

    #[test]
    fn tri_renders_the_api_words_not_booleans() {
        assert_eq!(Tri::Any.as_str(), "any");
        assert_eq!(Tri::Only.as_str(), "true");
        assert_eq!(Tri::Exclude.as_str(), "false");
        assert_eq!(Tri::default(), Tri::Exclude);
    }

    #[test]
    fn pairs_render_as_comma_separated_and_omit_empties() {
        let q = AssetQuery {
            dimensions: vec![Dimensions::D600x900, Dimensions::D342x482],
            nsfw: Some(Tri::Any),
            oneoftag: vec!["humor".into()],
            page: Some(2),
            limit: Some(50),
            ..Default::default()
        };
        let pairs = q.to_pairs();
        let get = |k: &str| {
            pairs
                .iter()
                .find(|(pk, _)| *pk == k)
                .map(|(_, v)| v.clone())
        };

        assert_eq!(get("dimensions"), Some("600x900,342x482".into()));
        assert_eq!(get("nsfw"), Some("any".into()));
        assert_eq!(get("oneoftag"), Some("humor".into()));
        assert_eq!(get("page"), Some("2".into()));
        assert_eq!(get("limit"), Some("50".into()));
        assert_eq!(get("styles"), None);
        assert_eq!(get("humor"), None, "an unset filter must be omitted");
    }

    #[test]
    fn an_empty_query_sends_nothing_at_all() {
        assert!(AssetQuery::default().to_pairs().is_empty());
    }
}
